# Generated by Django 6.0.6 on 2026-07-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
