# Generated by Django 6.0.6 on 2026-07-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_authcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
